---
title: "Exploring West African fisheries data with R"
author: "Stanley"
date: "10/04/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# LOAD LIBRARY
```{r}
require(tidyverse)
require(rfisheries)

```

# RETRIEVE DATA 
```{r}
annual_landings <- of_landings()
annual_landings

annual_landings %>% 
  ggplot(aes(year, catch)) +
  geom_line() + 
  labs(y = "Catch (MT)", 
       x = "Year", 
       title = "Global fish catch since 1950")

```

```{r}
# get country codes
 country_code <- of_country_codes()
filter(country_code, country == "CIV")

# Visualize that of Nigeria
of_landings(country = "NGA") %>% 
  ggplot(aes(year, catch)) + 
  geom_line() +
    labs(y = "Catch (MT)", 
       x = "Year", 
       title = "Record of Fish caught for Nigeria since 1950")
```


```{r}
# Visualise data for the whole of the west african region
west_african_countries <- tibble(code = c("NGA", "GHA", "SEN", "TGO", "CIV", "CPV", "BFA", "BEN", 
                                          "MLI", "LBR", "GMB", "NER", "SLE", "GIN", "GNB", "MRT"), 
                                 name = c("Nigeria", "Ghana", "Senegal", "Togo", "Côte d'Ivoire", 
                                          "Cape Verde", "Burkina faso", "Benin", "Mali", "Liberia", 
                                          "Gambia", "Niger", "Sierra Leone", "Guinea", "Guinea Bissua", 
                                          "Mauritania"))

landing_data = list()
for (catches in 1:nrow(west_african_countries)) {
  landing_data[[catches]] <- of_landings(country = west_african_countries$code[catches]) %>% 
    rename(code = country) %>% 
    mutate(name = west_african_countries$name[catches])
}

landing_data <- landing_data %>% bind_rows()
# visualize the data
ggplot(landing_data, aes(year, catch/1000, col=name)) +
  geom_line(size = 1) +
  scale_x_continuous(breaks = seq(1955, 2015, 20))

ggplot(landing_data, aes(year, catch/1000, col=name)) +
  geom_line(size = 1) +
  scale_x_continuous(breaks = seq(1955, 2015, 20)) +
  facet_wrap(vars(name), scales = "free_y")
```

